// Generated by RcppR6 (0.2.4): do not edit by hand
#include <MalariaIBM.h>

// [[Rcpp::export]]
MalariaIBM::test test__ctor(int N_new) {
  return MalariaIBM::test(N_new);
}
// [[Rcpp::export]]
int test__get_N(MalariaIBM::RcppR6::RcppR6<MalariaIBM::test> obj_) {
  return obj_->get_N();
}
// [[Rcpp::export]]
void test__set_N(MalariaIBM::RcppR6::RcppR6<MalariaIBM::test> obj_, int N_new) {
  obj_->set_N(N_new);
}
// [[Rcpp::export]]
void test__get_memLoc(MalariaIBM::RcppR6::RcppR6<MalariaIBM::test> obj_) {
  obj_->get_memLoc();
}


