// Generated by RcppR6 (0.2.4): do not edit by hand
#ifndef _MALARIAIBM_RCPPR6_PRE_HPP_
#define _MALARIAIBM_RCPPR6_PRE_HPP_

#include <RcppCommon.h>


namespace MalariaIBM {
namespace RcppR6 {
template <typename T> class RcppR6;
}
}

namespace MalariaIBM { class test; }

namespace Rcpp {
template <typename T> SEXP wrap(const MalariaIBM::RcppR6::RcppR6<T>&);
namespace traits {
template <typename T> class Exporter<MalariaIBM::RcppR6::RcppR6<T> >;
}

template <> SEXP wrap(const MalariaIBM::test&);
template <> MalariaIBM::test as(SEXP);
}

#endif
