# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_hello_world <- function() {
    .Call('_MalariaIBM_rcpp_hello_world', PACKAGE = 'MalariaIBM')
}

test__ctor <- function(N_new) {
    .Call('_MalariaIBM_test__ctor', PACKAGE = 'MalariaIBM', N_new)
}

test__get_N <- function(obj_) {
    .Call('_MalariaIBM_test__get_N', PACKAGE = 'MalariaIBM', obj_)
}

test__set_N <- function(obj_, N_new) {
    invisible(.Call('_MalariaIBM_test__set_N', PACKAGE = 'MalariaIBM', obj_, N_new))
}

test__get_memLoc <- function(obj_) {
    invisible(.Call('_MalariaIBM_test__get_memLoc', PACKAGE = 'MalariaIBM', obj_))
}

