## Generated by RcppR6: do not edit by hand
## Version: 0.2.4
## Hash: b6636d9eddfec9a868123a5dc48fe958

##' @importFrom Rcpp evalCpp
##' @importFrom R6 R6Class
##' @useDynLib MalariaIBM
NULL

##' i'm a test
##' @title test class
##' @section Methods:
##'   * i'm a method: write me!
##' @section Fields:
##'   * i'm a field: write me!
##' @export
`test` <- function(N_new) {
  test__ctor(N_new)
}
.R6_test <-
  R6::R6Class(
    "test",
    inherit=,
    portable=TRUE,
    public=list(
      .ptr=NULL,
      initialize = function(ptr) {
        self$.ptr <- ptr
      },
      get_N = function() {
        test__get_N(self)
      },
      set_N = function(N_new) {
        test__set_N(self, N_new)
      },
      get_memLoc = function() {
        test__get_memLoc(self)
      }),
    active=list())


